"use client";

/**
 * HorizonCard: renders a single horizon prediction (D1 / W1 / M1).
 *
 * Includes an info icon button that opens a modal with the narrative
 * explanation generated by the backend (heuristic or Claude).
 */
import { useState, type JSX } from "react";
import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react";
import {
  ArrowDown01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  InformationCircleIcon,
} from "@hugeicons/core-free-icons";

import { ExplanationModal } from "@/components/ExplanationModal";
import { formatDate, formatMoney, formatPct } from "@/lib/format";

export interface HorizonCardProps {
  horizon: "D1" | "W1" | "M1";
  targetDate: string;
  baseClose: number;
  predictedClose: number;
  predictedPct: number;
  direction: "ALTA" | "BAIXA" | "NEUTRO";
  explanation?: string | null;
}

const HORIZON_LABELS: Record<HorizonCardProps["horizon"], string> = {
  D1: "Amanhã",
  W1: "+7 dias",
  M1: "+30 dias",
};

function toneFor(direction: HorizonCardProps["direction"]): {
  text: string;
  badge: string;
  arrowIcon: IconSvgElement;
} {
  if (direction === "ALTA") {
    return {
      text: "text-emerald-400",
      badge: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
      arrowIcon: ArrowUp01Icon,
    };
  }
  if (direction === "BAIXA") {
    return {
      text: "text-red-400",
      badge: "bg-red-500/20 text-red-300 border-red-500/40",
      arrowIcon: ArrowDown01Icon,
    };
  }
  return {
    text: "text-yellow-300",
    badge: "bg-yellow-500/20 text-yellow-200 border-yellow-500/40",
    arrowIcon: ArrowRight01Icon,
  };
}

export function HorizonCard({
  horizon,
  targetDate,
  baseClose,
  predictedClose,
  predictedPct,
  direction,
  explanation,
}: HorizonCardProps): JSX.Element {
  const tone = toneFor(direction);
  const [open, setOpen] = useState(false);
  const title = `${HORIZON_LABELS[horizon]} - ${direction}`;
  return (
    <section className="rounded-xl border border-neutral-800 bg-neutral-900 p-5 shadow-sm">
      <header className="flex items-center justify-between">
        <h3 className="text-sm font-semibold text-neutral-300">
          {HORIZON_LABELS[horizon]}
        </h3>
        <div className="flex items-center gap-2">
          <span
            className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-xs font-semibold ${tone.badge}`}
            aria-label={`Tendência ${direction}`}
          >
            {direction}
            <HugeiconsIcon
              icon={tone.arrowIcon}
              size={14}
              strokeWidth={2}
              aria-hidden
            />
          </span>
          <button
            type="button"
            onClick={() => setOpen(true)}
            title="Por que essa tendência?"
            aria-label="Por que essa tendência?"
            className="rounded-full border border-neutral-800 p-1 text-neutral-400 transition hover:border-neutral-600 hover:bg-neutral-800 hover:text-neutral-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500/60"
          >
            <HugeiconsIcon
              icon={InformationCircleIcon}
              size={16}
              strokeWidth={1.6}
              aria-hidden
            />
          </button>
        </div>
      </header>
      <p className="mt-3 text-2xl font-bold text-neutral-50">
        {formatMoney(predictedClose)}
      </p>
      <p className={`mt-1 text-sm font-semibold ${tone.text}`}>
        {formatPct(predictedPct)}
      </p>
      <dl className="mt-3 grid grid-cols-2 gap-2 text-xs text-neutral-400">
        <div>
          <dt>Base</dt>
          <dd className="font-mono text-neutral-300">{formatMoney(baseClose)}</dd>
        </div>
        <div>
          <dt>Alvo</dt>
          <dd className="font-mono text-neutral-300">{formatDate(targetDate)}</dd>
        </div>
      </dl>
      <ExplanationModal
        open={open}
        onClose={() => setOpen(false)}
        title={title}
        explanation={explanation}
      />
    </section>
  );
}
