"use client";

/**
 * HorizonCard: renders a single horizon prediction (D1 / W1 / M1).
 *
 * Includes an info icon button that opens a modal with the narrative
 * explanation generated by the backend (heuristic or Claude).
 */
import { useState, type JSX } from "react";

import { ExplanationModal } from "@/components/ExplanationModal";
import { formatDate, formatMoney, formatPct } from "@/lib/format";

export interface HorizonCardProps {
  horizon: "D1" | "W1" | "M1";
  targetDate: string;
  baseClose: number;
  predictedClose: number;
  predictedPct: number;
  direction: "ALTA" | "BAIXA" | "NEUTRO";
  explanation?: string | null;
}

const HORIZON_LABELS: Record<HorizonCardProps["horizon"], string> = {
  D1: "Amanhã",
  W1: "+7 dias",
  M1: "+30 dias",
};

function toneFor(direction: HorizonCardProps["direction"]): {
  text: string;
  badge: string;
  arrow: string;
} {
  if (direction === "ALTA") {
    return {
      text: "text-emerald-400",
      badge: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
      arrow: "↑",
    };
  }
  if (direction === "BAIXA") {
    return {
      text: "text-red-400",
      badge: "bg-red-500/20 text-red-300 border-red-500/40",
      arrow: "↓",
    };
  }
  return {
    text: "text-yellow-300",
    badge: "bg-yellow-500/20 text-yellow-200 border-yellow-500/40",
    arrow: "→",
  };
}

function InfoIcon(): JSX.Element {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      strokeWidth={1.6}
      stroke="currentColor"
      className="h-4 w-4"
      aria-hidden="true"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z"
      />
    </svg>
  );
}

export function HorizonCard({
  horizon,
  targetDate,
  baseClose,
  predictedClose,
  predictedPct,
  direction,
  explanation,
}: HorizonCardProps): JSX.Element {
  const tone = toneFor(direction);
  const [open, setOpen] = useState(false);
  const title = `${HORIZON_LABELS[horizon]} - ${direction}`;
  return (
    <section className="rounded-xl border border-neutral-800 bg-neutral-900 p-5 shadow-sm">
      <header className="flex items-center justify-between">
        <h3 className="text-sm font-semibold text-neutral-300">
          {HORIZON_LABELS[horizon]}
        </h3>
        <div className="flex items-center gap-2">
          <span
            className={`rounded-full border px-2 py-0.5 text-xs font-semibold ${tone.badge}`}
            aria-label={`Tendência ${direction}`}
          >
            {direction} {tone.arrow}
          </span>
          <button
            type="button"
            onClick={() => setOpen(true)}
            title="Por que essa tendencia?"
            aria-label="Por que essa tendencia?"
            className="rounded-full border border-neutral-800 p-1 text-neutral-400 hover:border-neutral-600 hover:bg-neutral-800 hover:text-neutral-100 focus:outline-none focus:ring-2 focus:ring-emerald-500/50"
          >
            <InfoIcon />
          </button>
        </div>
      </header>
      <p className="mt-3 text-2xl font-bold text-neutral-50">
        {formatMoney(predictedClose)}
      </p>
      <p className={`mt-1 text-sm font-semibold ${tone.text}`}>
        {formatPct(predictedPct)}
      </p>
      <dl className="mt-3 grid grid-cols-2 gap-2 text-xs text-neutral-400">
        <div>
          <dt>Base</dt>
          <dd className="font-mono text-neutral-300">{formatMoney(baseClose)}</dd>
        </div>
        <div>
          <dt>Alvo</dt>
          <dd className="font-mono text-neutral-300">{formatDate(targetDate)}</dd>
        </div>
      </dl>
      <ExplanationModal
        open={open}
        onClose={() => setOpen(false)}
        title={title}
        explanation={explanation}
      />
    </section>
  );
}
